const uz = {
	viewOrder: "Buyurtmani ko'rish",
	orders: 'Buyurtmalar',
	cancel: 'Bekor qilish',
	orderId: 'Buyurtma id',
	products: 'Mahsulotlar',
	product: 'Mahsulot',
	consumerName: 'Mijoz ismi',
	consumerAddress: 'Mijoz manzili',
	allPrice: 'Jami narxi',
	status: 'Status',
	date: 'Sanasi',
	unitPrice: 'Donasining narxi',
	quantity: 'Miqdori',
	consumer: 'Mijoz',
	orderInfo: 'Buyurtma haqida ma`lumot',
	consumerNumber: 'Telefon nomeri',
	paymentMethod: 'To`lov turi',
	page: 'Sahifa',
	enter: 'kiriting',
	content_uz: "ma'lumotini o`zbekcha",
	content_ru: "ma'lumotini ruscha",
	url: 'URL ni',
	title_uz: 'sarlavhasini o`zbekcha',
	title_ru: 'sarlavhasini ruscha',
	success: 'muvaffaqiyatli',
	update: 'yangilandi',
	add: "qo'shildi",
	name: 'nomi',
	description: 'tavsifi',
	edit: 'Tahrirlash',
	delete: 'O`chirish',
	changeUrl: 'Bu URL band, iltimos URL ni o`zgartiring!',
	viewPage: 'Sahifani ko`rish',
	main: 'Asosiy',
	attributes: 'Attributlar',
	category: 'Kategoriya',
	categorys: 'Kategoriyalar',
	pages: 'Sahifalar',
	brands: 'Brendlar',
	events: 'Bannerlar',
	addCategory: 'Kategoriya qo`shish',
	categoryNameUz: 'Kategoriya o`zbekcha nomi',
	categoryNameRu: 'Kategoriya ruscha nomi',
	addBrand: 'Brand qo`shish',
	deleteBrand: 'Brandni o`chirmoqchimisz',
	yes: 'Ha',
	no: "yo'q",
	brandNameUz: 'Brand nomini o`zbekcha kiriting',
	brandNameRu: 'Brand nomini ruscha kiriting',
	brandName: 'Brand nomi',
	addBanner: 'Banner qo`shish',
	img: 'Rasm',
	bannerName: 'Banner nomi',
	bannerPosition: 'Banner pozitsiyasi',
	viewBanner: "Bannerni ko'rish",
	deleteBanner: 'Bannerni o`chirmoqchimisz',
	save: 'Saqlash',
}

const ru = {
	viewOrder: 'Просмотреть заказ',
	orders: 'Заказы',
	cancel: 'Отмена',
	orderId: 'Номер заказа',
	products: 'Товары',
	product: 'Товар',
	consumerName: 'Имя Клиента',
	consumerAddress: 'Адрес клиента',
	allPrice: 'Итоговая цена',
	status: 'Статус',
	date: 'Дата',
	unitPrice: 'Цена за единицу товара',
	quantity: 'Количество',
	consumer: 'Клиент',
	orderInfo: 'Запросить информацию',
	consumerNumber: 'Номер телефона',
	paymentMethod: 'Тип платежа',
	page: 'Страница',
	enter: 'войти',
	content_uz: 'информация на узбекском',
	content_ru: 'информация на русском',
	url: 'URL-адрес',
	title_uz: 'название на узбекском языке',
	title_ru: 'название на русском языке',
	success: 'успешно',
	update: 'обновлена',
	add: 'добавлен',
	name: 'название',
	description: 'описание',
	edit: 'Редактировать',
	delete: 'Удалить',
	changeUrl: 'Этот URL-адрес занят, пожалуйста, измените URL-адрес!',
	viewPage: 'Просмотреть страницу',
	main: 'Главный',
	attributes: 'Атрибуты',
	category: 'Категория',
	categorys: 'Категории',
	pages: 'Страницы',
	brands: 'Бренды',
	events: 'Баннеры',
	addCategory: 'Добавить категорию',
	categoryNameUz: 'Категория Узбекское название',
	categoryNameRu: 'Категория Русское название',
	addBrand: 'Добавить бренд',
	deleteBrand: 'Вы хотите удалить бренд',
	yes: 'Да',
	no: 'Нет',
	brandNameUz: 'Введите название бренда на узбекском языке',
	brandNameRu: 'Введите название бренда на русском языке',
	brandName: 'Имя бренда',
	addBanner: 'Добавить баннер',
	img: 'Картина',
	bannerName: 'Название баннера',
	bannerPosition: 'Позиция баннера',
	viewBanner: 'Посмотреть баннер',
	deleteBanner: 'Вы хотите удалить баннер?',
	save: 'Сохранять',
}

export const languages = { uz, ru }
